appname: hrportal
replicaCount: 1
image:
  repository: rohitazure369/pratech:hrportal
  pullPolicy: Always
resources:
  limits:
    cpu: "0.1"
    memory: "128Mi"
  requests:
    cpu: "0.1"
    memory: "128Mi"

service: 
  extport: 9104
  intport: 80
