appname: resume-api
replicaCount: 1
image:
  repository: rohitazure369/pratech:resume-api
  pullPolicy: always
resources:
  limits:
    cpu: "0.1"
    memory: "128Mi"
  requests:
    cpu: "0.1"
    memory: "128Mi"

service: 
  extport: 8102
  intport: 5002
